/*Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55,
89, ... By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.*/
limit = 4000000
sum = 0
a = 1
b = 1
c = a+b
while c < limit:
  
  sum += c
  a = b + c
  b = c + a
  c = a + b
print(sum)


#4.2)Each new term in the Fibonacci sequence is generated by adding the previous two
#terms. By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55,
#89, ... By considering the terms in the Fibonacci sequence whose values do not
#exceed four million, find the sum of the even-valued terms.
a=0;b=1;sum=0
while a<=4000000:
    if a%2==0:
        sum=sum+a
    a,b=b,a+b #swapping of two numbers   a=1,b=1
print("sum of even fibonacci numbers is",sum)

OUTPUT:
 sum of even fibonacci numbers is 4613732
